const STORAGE_KEY='chestnoAppV1';
const colors=['#b9ff36','#8b7cff','#ff5c45','#45d7ff','#ffcf45'];
const scenarios=[
 {cat:'18+',q:'Показать родителям всю историю браузера или друзьям все личные переписки?',a:'История родителям',b:'Переписки друзьям',c:['Удалять ничего нельзя.','Архив за последние пять лет.','Объясняться после просмотра запрещено.']},
 {cat:'18+',q:'Обосраться на первом свидании или назвать партнёра именем бывшего во время секса?',a:'Провал на свидании',b:'Имя бывшего',c:['О случившемся узнают общие друзья.','Сбежать сразу нельзя.','Второго шанса не будет.']},
 {cat:'18+',q:'Год без секса или год без музыки?',a:'Без секса',b:'Без музыки',c:['Случайно услышанное тоже считается.','Исключений по праздникам нет.','Выбор начинается прямо сейчас.']},
 {cat:'18+',q:'Каждый твой оргазм сопровождается сиреной или каждое враньё — громким мяуканьем?',a:'Сирена',b:'Мяуканье',c:['Звук слышен в радиусе ста метров.','Убавить громкость невозможно.','Окружающие знают причину звука.']},
 {cat:'18+',q:'Прийти голым на чужую свадьбу или в свадебном костюме на похороны?',a:'Голым на свадьбу',b:'Нарядным на похороны',c:['Уйти раньше окончания нельзя.','Там будут все знакомые.','Фотограф работает весь вечер.']},
 {cat:'18+',q:'Навсегда отказаться от алкоголя или от секса?',a:'Без алкоголя',b:'Без секса',c:['Даже по праздникам.','Навсегда означает навсегда.','Без лазеек и замен.']},
 {cat:'ПОЗОР',q:'Телефон без пароля остаётся на вечеринке или твой дневник читают вслух семье?',a:'Телефон на вечеринке',b:'Дневник семье',c:['В телефоне открыта последняя переписка.','Все внимательно досмотрят до конца.','Забрать вещь раньше нельзя.']},
 {cat:'ПОЗОР',q:'Случайно отправить голосовое с обсуждением человека ему самому или признаться, что следишь за его страницей?',a:'Отправить голосовое',b:'Признаться в слежке',c:['Удалить сообщение уже нельзя.','Человек сразу отвечает.','Это тот, кто тебе нравится.']},
 {cat:'БЫТ',q:'Месяц не мыться или месяц спать только по три часа?',a:'Не мыться',b:'Спать по 3 часа',c:['Дезодорант использовать нельзя.','Отпуск и больничный не дадут.','Окружающие знают о выборе.']},
 {cat:'БЫТ',q:'Жить с родителями до 35 или каждый месяц переезжать к новому случайному соседу?',a:'С родителями',b:'Случайные соседи',c:['Отдельное жильё недоступно.','Соседей выбирает случай.','Правила дома устанавливаешь не ты.']},
 {cat:'БЫТ',q:'Пользоваться только холодным душем или никогда больше не есть горячую еду?',a:'Холодный душ',b:'Холодная еда',c:['Так будет всю жизнь.','Погода ничего не меняет.','Подогреть даже чай нельзя.']},
 {cat:'ДЕНЬГИ',q:'Получить миллион сейчас или десять миллионов через десять лет?',a:'Миллион сейчас',b:'Ждать 10 лет',c:['Инфляция неизвестна.','Получить раньше невозможно.','О решении никто не узнает.']},
 {cat:'ДЕНЬГИ',q:'Жить бесплатно с неприятным человеком или отдавать половину дохода за одиночество?',a:'Бесплатно вдвоём',b:'Дорого одному',c:['Переехать ближайшие пять лет нельзя.','Человек не станет приятнее.','Доход останется обычным.']},
 {cat:'ДЕНЬГИ',q:'Потерять все накопления или год работать бесплатно?',a:'Потерять накопления',b:'Работать бесплатно',c:['Долгов не появится.','Помощи от семьи не будет.','Выбрать другую работу нельзя.']},
 {cat:'ОТНОШЕНИЯ',q:'Узнать всю правду о партнёре или сохранить спокойствие и никогда не проверять?',a:'Узнать правду',b:'Не проверять',c:['Назад это знание не вернуть.','Спросить напрямую нельзя.','Ответ может всё изменить.']},
 {cat:'ОТНОШЕНИЯ',q:'Вернуть одного человека из прошлого или гарантированно встретить нового близкого человека?',a:'Вернуть прошлое',b:'Встретить нового',c:['Оба варианта настоящие.','Решение нужно принять сегодня.','Второй возможности не будет.']},
 {cat:'ОТНОШЕНИЯ',q:'Всегда понимать чужие чувства или уметь идеально объяснять свои?',a:'Понимать других',b:'Объяснять себя',c:['Второй навык навсегда останется слабым.','Способность нельзя отключить.','Это касается всех людей.']},
 {cat:'ДРУЗЬЯ',q:'Сдать друга ради собственной безопасности или взять общую вину на себя?',a:'Сдать друга',b:'Взять вину',c:['Друг поступил бы с тобой так же.','Никто не узнает о мотивах.','Последствия будут реальными.']},
 {cat:'ДРУЗЬЯ',q:'Узнать, что друзья обсуждают тебя, или никогда не знать их настоящего мнения?',a:'Узнать всё',b:'Не знать',c:['Они не узнают, что ты слышал.','Изменить разговор нельзя.','Там будет и хорошее, и плохое.']},
 {cat:'МОЗГ',q:'Удалить самое плохое воспоминание вместе с одним хорошим или оставить всё?',a:'Удалить оба',b:'Оставить всё',c:['Выбрать хорошее воспоминание нельзя.','Навыки сохранятся.','Вернуть память невозможно.']},
 {cat:'МОЗГ',q:'Знать дату своей смерти или причину?',a:'Знать дату',b:'Знать причину',c:['Изменить будущее нельзя.','Рассказать кому-либо нельзя.','Ответ будет абсолютно точным.']},
 {cat:'МОЗГ',q:'Всегда говорить правду или никогда больше не говорить?',a:'Только правда',b:'Полное молчание',c:['Писать вместо речи нельзя.','Правда будет полной.','Исключений ради близких нет.']},
 {cat:'АБСУРД',q:'Лизнуть поручень в метро или выпить стакан воды из чужой ванны?',a:'Поручень метро',b:'Вода из ванны',c:['Метро в час пик.','Вода после купания.','Прополоскать рот сразу нельзя.']},
 {cat:'АБСУРД',q:'Иметь голос навигатора или смеяться звуком старого модема?',a:'Голос навигатора',b:'Смех модема',c:['Все замечают странность.','Вернуть обычный звук нельзя.','Это начинается завтра.']},
 {cat:'БУДУЩЕЕ',q:'Жить в идеальном виртуальном мире или несовершенной реальности?',a:'Идеальная иллюзия',b:'Реальная жизнь',c:['Внутри иллюзии ты не узнаешь правду.','Вернуться после выбора нельзя.','Близкие могут выбрать иначе.']}
];
let state=loadState(), currentQuestion=null, pendingProfile=false;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function loadState(){try{const s=JSON.parse(localStorage.getItem(STORAGE_KEY));if(s&&s.version===1)return s}catch{}return{version:1,profiles:[],activeId:null,results:{},settings:{accent:'#b9ff36',theme:'dark',scale:100,radius:'10px',motion:true,compact:false}}}
function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state))}
function profile(){return state.profiles.find(p=>p.id===state.activeId)||null}
function hash(str){let h=2166136261;for(let i=0;i<str.length;i++){h^=str.charCodeAt(i);h=Math.imul(h,16777619)}return h>>>0}
function rng(seed){return()=>{seed|=0;seed=seed+0x6D2B79F5|0;let t=Math.imul(seed^seed>>>15,1|seed);t=t+Math.imul(t^t>>>7,61|t)^t;return((t^t>>>14)>>>0)/4294967296}}
function qid(q){return 'q'+hash(q.q+'|'+q.condition).toString(36)}
function generateQuestion(force=false){const p=profile();if(!p){openProfileModal();return}if(!force&&p.current){currentQuestion=p.current;renderPoll();return}p.counter=(p.counter||0)+1;let attempt=0,q;do{const r=rng(hash(p.id+':'+p.counter+':'+attempt));const base=scenarios[Math.floor(r()*scenarios.length)];const condition=base.c[Math.floor(r()*base.c.length)];q={cat:base.cat,q:base.q,a:base.a,b:base.b,condition};q.id=qid(q);attempt++}while((p.seen||[]).includes(q.id)&&attempt<100);p.seen=[...(p.seen||[]),q.id].slice(-100);p.current=q;currentQuestion=q;save();renderPoll()}
function renderPoll(){const p=profile(),q=currentQuestion;if(!p||!q)return;$('#pollCategory').textContent=q.cat;$('#questionSerial').textContent='ВОПРОС #'+String(p.counter||1).padStart(3,'0');$('#pollQuestion').textContent=q.q;$('#pollCondition').textContent=q.condition;const result=state.results[q.id]||{voters:{}};const own=result.voters?.[p.id];$('#choiceGrid').innerHTML=`<button class="choice ${own===0?'selected':''}" data-choice="0" ${own!==undefined?'disabled':''}><span class="choice-key">A</span><b>${q.a}</b><span class="choice-percent">—</span><i></i></button><div class="or">ИЛИ</div><button class="choice ${own===1?'selected':''}" data-choice="1" ${own!==undefined?'disabled':''}><span class="choice-key">B</span><b>${q.b}</b><span class="choice-percent">—</span><i></i></button>`;$$('.choice').forEach(b=>b.onclick=()=>castVote(+b.dataset.choice));if(own!==undefined)revealResult(result,own);else{$('#realVoteCount').textContent='Пока нет ответа этого профиля';$('#resultNote').textContent='Проценты появятся после выбора'}updateDashboard()}
function castVote(choice){const p=profile(),q=currentQuestion;if(!p||!q)return;let r=state.results[q.id]||{voters:{}};if(r.voters[p.id]!==undefined)return;r.voters[p.id]=choice;state.results[q.id]=r;p.answers=p.answers||[];p.answers.unshift({qid:q.id,q:q.q,cat:q.cat,choice,answer:choice?q.b:q.a,ts:Date.now()});p.lastActive=Date.now();p.current=null;save();revealResult(r,choice);updateDashboard();renderPeople();toast('Ответ записан честно')}
function revealResult(r,own){const vals=Object.values(r.voters||{}),a=vals.filter(v=>v===0).length,b=vals.length-a,total=vals.length,pa=Math.round(a/total*100),pb=100-pa;$$('.choice').forEach((el,i)=>{el.disabled=true;el.querySelector('.choice-percent').textContent=(i?pb:pa)+'%';el.querySelector('i').style.width=(i?pb:pa)+'%';if(i===own)el.classList.add('selected')});$('#realVoteCount').textContent=total===1?'1 реальный ответ на этом устройстве':`${total} реальных ответа на этом устройстве`;$('#resultNote').textContent=total<2?'Для сравнения нужен ещё один участник':(own===(a>=b?0:1)?'Твой выбор совпал с большинством':'Ты выбрал мнение меньшинства')}
function createProfile(name){const id='p'+Date.now().toString(36)+Math.random().toString(36).slice(2,6);state.profiles.push({id,name,color:colors[state.profiles.length%colors.length],answers:[],seen:[],counter:0,lastActive:Date.now()});state.activeId=id;save();closeProfileModal();refreshProfile();generateQuestion(true);toast('Профиль создан')}
function refreshProfile(){const p=profile();$('#topName').textContent=p?p.name:'Создать профиль';$('#topMeta').textContent=p?`${p.answers?.length||0} ответов · локально`:'Нажмите, чтобы начать';$('#topAvatar').textContent=p?p.name[0].toUpperCase():'?';$('#topAvatar').style.background=p?.color||'var(--accent)';renderProfileMenu();renderPeople();updateDashboard();renderInsights()}
function renderProfileMenu(){const box=$('#profileMenu');box.innerHTML=state.profiles.map(p=>`<button data-profile="${p.id}"><span class="small-avatar" style="background:${p.color}">${escapeHtml(p.name[0].toUpperCase())}</span><span>${escapeHtml(p.name)}${p.id===state.activeId?' · активен':''}</span></button>`).join('')+`<button class="add-profile" data-add><svg style="width:17px;height:17px;fill:none;stroke:currentColor"><use href="#i-plus"/></svg> Добавить человека</button>`;box.querySelectorAll('[data-profile]').forEach(b=>b.onclick=()=>switchProfile(b.dataset.profile));box.querySelector('[data-add]').onclick=()=>openProfileModal()}
function switchProfile(id){state.activeId=id;save();$('#profileMenu').classList.remove('open');refreshProfile();const p=profile();currentQuestion=p.current||null;generateQuestion(!currentQuestion);showView('vote')}
function profileAgreement(p){let comparable=0,agree=0;(p.answers||[]).forEach(x=>{const vals=Object.values(state.results[x.qid]?.voters||{});if(vals.length<2)return;comparable++;const a=vals.filter(v=>v===0).length;const maj=a>=vals.length-a?0:1;if(x.choice===maj)agree++});return comparable?Math.round(agree/comparable*100):null}
function updateDashboard(){const p=profile(),n=p?.answers?.length||0,rate=p?profileAgreement(p):null;$('#sideAnswers').textContent=n;$('#sideMatch').textContent=rate===null?'—':rate+'%';$('#sideMatchBar').style.width=(rate||0)+'%'}
function renderPeople(){const rows=$('#peopleRows');const sorted=[...state.profiles].sort((a,b)=>(b.answers?.length||0)-(a.answers?.length||0));rows.innerHTML=sorted.map((p,i)=>{const rate=profileAgreement(p);return `<tr><td>${String(i+1).padStart(2,'0')}</td><td><div class="person-cell"><span class="small-avatar" style="background:${p.color}">${escapeHtml(p.name[0].toUpperCase())}</span><span><b>${escapeHtml(p.name)}</b><small>${p.id===state.activeId?'<i class="active-tag">АКТИВЕН</i>':'Локальный профиль'}</small></span></div></td><td><b>${p.answers?.length||0}</b></td><td>${rate===null?'Недостаточно данных':rate+'%'}</td><td>${timeAgo(p.lastActive)}</td><td><button class="row-action" data-switch="${p.id}">Выбрать</button></td></tr>`}).join('');$('#emptyPeople').style.display=state.profiles.length?'none':'block';$$('[data-switch]').forEach(b=>b.onclick=()=>switchProfile(b.dataset.switch))}
function renderInsights(){const p=profile(),answers=p?.answers||[],rate=p?profileAgreement(p):null;$('#statAnswers').textContent=answers.length;$('#statAgreement').textContent=rate===null?'—':rate+'%';const counts={};answers.forEach(a=>counts[a.cat]=(counts[a.cat]||0)+1);$('#statCategory').textContent=Object.entries(counts).sort((a,b)=>b[1]-a[1])[0]?.[0]||'—';$('#historyList').innerHTML=answers.length?answers.slice(0,12).map(a=>`<div class="history-item"><span>${a.cat}</span><p>${escapeHtml(a.q)}</p><b>${escapeHtml(a.answer)}</b></div>`).join(''):'<div class="empty-history">Здесь появятся только реальные ответы выбранного профиля.</div>'}
function showView(name){$$('.view').forEach(v=>v.classList.toggle('active',v.id==='view-'+name));$$('.nav-item[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===name));$('#pageTitle').textContent={vote:'ВОПРОСЫ',people:'УЧАСТНИКИ',insights:'СТАТИСТИКА'}[name];if(name==='people')renderPeople();if(name==='insights')renderInsights();$('.sidebar').classList.remove('open')}
function openProfileModal(){pendingProfile=true;$('#profileModal').classList.add('open');$('#profileModal').setAttribute('aria-hidden','false');$('#profileCancel').style.display=state.profiles.length?'inline-flex':'none';$('#profileName').value='';setTimeout(()=>$('#profileName').focus(),50)}
function closeProfileModal(){pendingProfile=false;$('#profileModal').classList.remove('open')}
function applySettings(){const s=state.settings;document.documentElement.dataset.theme=s.theme||'dark';document.documentElement.style.setProperty('--accent',s.accent||'#b9ff36');document.documentElement.style.setProperty('--scale',(s.scale||100)/100);document.documentElement.style.setProperty('--radius',s.radius||'10px');document.body.classList.toggle('no-motion',s.motion===false);document.body.classList.toggle('compact',!!s.compact);$('#themeSelect').value=s.theme||'dark';$('#fontSize').value=s.scale||100;$('#fontOutput').textContent=(s.scale||100)+'%';$('#motionToggle').checked=s.motion!==false;$('#compactToggle').checked=!!s.compact;$$('#accentSwatches button').forEach(b=>b.classList.toggle('active',b.dataset.color===(s.accent||'#b9ff36')));$$('#radiusChoice button').forEach(b=>b.classList.toggle('active',b.dataset.radius===(s.radius||'10px')))}
function timeAgo(ts){if(!ts)return '—';const m=Math.floor((Date.now()-ts)/60000);if(m<1)return 'только что';if(m<60)return `${m} мин. назад`;const h=Math.floor(m/60);if(h<24)return `${h} ч. назад`;return new Date(ts).toLocaleDateString('ru-RU')}
function escapeHtml(s=''){return s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function toast(text){const t=$('#toast');t.textContent=text;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1800)}
$$('[data-view]').forEach(b=>b.onclick=()=>showView(b.dataset.view));$('#newQuestion').onclick=()=>{const panel=$('#pollPanel');panel.classList.add('changing');setTimeout(()=>{generateQuestion(true);panel.classList.remove('changing')},180)};$('#addPerson').onclick=openProfileModal;$('#profileButton').onclick=e=>{e.stopPropagation();if(!state.profiles.length)openProfileModal();else $('#profileMenu').classList.toggle('open')};document.addEventListener('click',()=>$('#profileMenu').classList.remove('open'));$('#profileMenu').onclick=e=>e.stopPropagation();$('#profileSave').onclick=()=>{const n=$('#profileName').value.trim();if(n.length<2)return toast('Введите имя минимум из 2 символов');createProfile(n)};$('#profileName').onkeydown=e=>{if(e.key==='Enter')$('#profileSave').click()};$('#profileCancel').onclick=closeProfileModal;$('#mobileMenu').onclick=()=>$('.sidebar').classList.toggle('open');
$('#settingsOpen').onclick=()=>{$('#settingsDrawer').classList.add('open');applySettings()};$$('[data-close-settings]').forEach(b=>b.onclick=()=>$('#settingsDrawer').classList.remove('open'));$$('#accentSwatches button').forEach(b=>b.onclick=()=>{state.settings.accent=b.dataset.color;save();applySettings()});$('#themeSelect').onchange=e=>{state.settings.theme=e.target.value;save();applySettings()};$('#fontSize').oninput=e=>{state.settings.scale=+e.target.value;save();applySettings()};$$('#radiusChoice button').forEach(b=>b.onclick=()=>{state.settings.radius=b.dataset.radius;save();applySettings()});$('#motionToggle').onchange=e=>{state.settings.motion=e.target.checked;save();applySettings()};$('#compactToggle').onchange=e=>{state.settings.compact=e.target.checked;save();applySettings()};$('#resetAppearance').onclick=()=>{state.settings={accent:'#b9ff36',theme:'dark',scale:100,radius:'10px',motion:true,compact:false};save();applySettings();toast('Внешний вид сброшен')};$('#eraseData').onclick=()=>{if(confirm('Удалить все профили, ответы и настройки с этого устройства?')){localStorage.removeItem(STORAGE_KEY);location.reload()}};
applySettings();refreshProfile();if(profile()){currentQuestion=profile().current||null;generateQuestion(!currentQuestion)}else setTimeout(openProfileModal,250);
